name: mlflow-env
channels:
  - conda-forge
dependencies:
  - python=3.12.9
  - pip<=25.1
  - pip:
    - pandas==2.2.3
    - scikit-learn==1.6.1
    - mlflow==2.19.0
    - matplotlib>=3.0
    - seaborn>=0.11
    - numpy>=1.20
    - dagshub>=0.3
    - python-dotenv>=0.19
    - imbalanced-learn>=0.8 
    - click>=8.0
