name: mlflow-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12.9
  - pip
  - pandas>=1.3
  - scikit-learn>=1.0
  - mlflow==2.13.0
  - matplotlib>=3.0
  - seaborn>=0.11
  - numpy>=1.20
  - dagshub>=0.3
  - python-dotenv>=0.19
  - imbalanced-learn>=0.8
  - pip:
    - click>=8.0
    - imbalanced-learn
