name: wine_quality_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - mlflow==2.19.0
      - scikit-learn==1.6.1
      - pandas==2.2.2
      - numpy==1.26.4
      - python-dotenv
