name: wine_quality_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - mlflow==2.19.0
      - scikit-learn
      - pandas
      - numpy
      - python-dotenv
