name: CI/CD MLflow Red Wine

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  EXPERIMENT_NAME: Red_Wine_Tunning
  CSV_URL: preprocessed_winequality-red.csv
  TARGET_VAR: quality
  MLFLOW_TRACKING_URI: https://dagshub.com/latifaharums/Membangun_model.mlflow/
  MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_TRACKING_USERNAME }}
  MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Check Env Variables
      run: |
        echo "CSV URL: $CSV_URL"
        echo "Experiment Name: $EXPERIMENT_NAME"
        echo "MLflow Tracking URI: $MLFLOW_TRACKING_URI"

    - name: Install MLflow and dotenv
      run: |
        python -m pip install --upgrade pip
        pip install mlflow python-dotenv

    - name: Run MLflow Project
      run: |
        mlflow run MLProject --env-manager=local --run-name rf_fixed_run

    - name: Install Python Dependencies from MLProject
      run: |
        pip install -r MLProject/requirements.txt

    - name: Download Model Artifact from MLflow
      run: |
        mlflow artifacts download \
          --run-id $RUN_ID \
          --artifact-path rf_best_model \
          --dst-path downloaded_artifact

    - name: Upload Artifact to GitHub Actions
      uses: actions/upload-artifact@v4
      with:
        name: rf_model_artifact
        path: downloaded_artifact/

    - name: Build Docker Model with MLflow
      run: |
        mlflow models build-docker --model-uri "runs:/$RUN_ID/rf_best_model" --name "red_wine_model"

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Tag Docker Image
      run: |
        docker tag red_wine_model ${{ secrets.DOCKER_USERNAME }}/red_wine_model:latest

    - name: Push Docker Image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/red_wine_model:latest
